/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareableCodeRouteImport } from './routes/$shareableCode'
import { Route as IndexRouteImport } from './routes/index'

const ShareableCodeRoute = ShareableCodeRouteImport.update({
  id: '/$shareableCode',
  path: '/$shareableCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shareableCode': typeof ShareableCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shareableCode': typeof ShareableCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shareableCode': typeof ShareableCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shareableCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shareableCode'
  id: '__root__' | '/' | '/$shareableCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareableCodeRoute: typeof ShareableCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$shareableCode': {
      id: '/$shareableCode'
      path: '/$shareableCode'
      fullPath: '/$shareableCode'
      preLoaderRoute: typeof ShareableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareableCodeRoute: ShareableCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
